theme = "CodeMeta-Pyramids"
baseurl = "/"
relativeurls = true
title = "The CodeMeta Project"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "\\.csv", "\\.R"]
publishDir = "../website"

[[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 1
[[menu.main]]
    name = "Crosswalk"
    url = "/crosswalk/"
    weight = 2
[[menu.main]]
    name = "Create"
    url = "/create/"
    weight = 3
[[menu.main]]
    name = "Terms"
    url = "/terms/"
    weight = 4
[[menu.main]]
    name = "User Guide"
    url = "/user-guide"
    weight = 5
[[menu.main]]
    name = "Developer Guide"
    url = "/developer-guide"
    weight = 6
[[menu.main]]
    name = "JSON-LD"
    url = "/jsonld"
    weight = 7
[[menu.main]]
    name = "Tools"
    url = "/tools"
    weight = 8

[[menu.footer]]
    name = "Source code on Github"
    url = "https://github.com/codemeta/"
    pre = "<i class='bi-github'></i>"
    weight = 1
[[menu.footer]]
    name = "Governance"
    url = "https://codemeta.github.io/governance/"
    weight = 2
[[menu.footer]]
    name = "Scicodes Consortium"
    url = "https://scicodes.net/"
    weight = 3


[params]
    name =  "codemeta"
    github =  "codemeta"
    repo = "codemeta.github.io"
    background = "img/pyramids.jpg"
    
    newslimit = 5
    feeds = [
        "https://softwareheritage.org/tag/codemeta/feed/"
    ]

    date_format = "Mon, Jan 2, 2006"
    description = "A Rosetta Stone for Software Metadata"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'pygments'

[markup.goldmark.parser.attribute]
    block = true # default is false
