name: Update news

on:
  schedule:
  # Get the feed every day at 1:13 UTC
    - cron: "13 1 * * *"
  # allow manual update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download File
      run: |
        curl https://www.softwareheritage.org/tag/codemeta/feed/ --output ./data/news.xml
      working-directory: ${{ github.workspace }}
    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git add ./data/news.xml
        git commit -m 'Update news feed'
        git push
